### ISSUE TITLE
Decouple From Concrete Classes

### ISSUE THREAD

**Issue by myriad-developers** [rbro112/Android-Indefinite-Pager-Indicator#16]
Literally all you need here is total postilions and current position. There's no reason you need a view pager or a recycler view for this and it limits it's uses.

**Comment by wching** [comment]
Maybe a PR with your initial thoughts/implementation would be a great start for all of us to discuss and come up with an amazing solution! 😃

**Comment by rbro112** [comment]
Similar to what Walter said above, a PR would be great to see your thoughts! Much of the implementation here is done for convenience sake. The original use case I built the indicator for was just RecyclerViews and ViewPagers, but you are right, it can be decoupled very easily from those two specific views.

For now, I'll leave it as is -- implementation is extremely simple in the library's current state (only about 2 lines of code to implement). Decoupling the indicator from VPs/RVs would likely abstract the implementation to a point where it is more difficult to implement for simple use cases.

**Comment by rbro112** [comment]
@myriad-developers I'm going to close this issue to keep the repo clean tomorrow. If you all have any suggestions or PR's in the works, let me know and I'll leave this open. For now though, I'll be closing sometime tomorrow evening.

**Comment by wching** [comment]
Closing issue as suggestion was not provided
