### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by miguelhincapie** [rbro112/Android-Indefinite-Pager-Indicator#28]
Hi there,

I just clone the project, tried to open it with AS and I got this error:

> Error:Could not read script 'C:\Users\xxxx\Documents\xxx\Android-Indefinite-Pager-Indicator\gradle\bintray_installer.gradle' as it does not exist.

It's been used in line 62 in library gradle, but I couldn't find it.

**Comment by rbro112** [comment]
@miguelhincapie that's a private file that I've left out of the project as it contains credentials I use to push versions of the library to Maven. You can simply remove line 62 and 63 from the IndefinitePagerIndicator module:

```
apply from: '../gradle/bintray_installer.gradle'
apply from: '../gradle/maven_installer.gradle'
```

Everything should work fine after this! Let me know if this doesn't work. I should probably look into this for future versions. -- I'll do this in a week or so when I become a full time Android dev again 😄
