### ISSUE TITLE
Programmatically customization

### ISSUE THREAD

**Issue by 5mi13** [rbro112/Android-Indefinite-Pager-Indicator#31]
How can I customize this view when it's creating programmatically? How to change dots colors, size, count,  for example?

**Comment by vipulasri** [comment]
Yeah, this is totally needed.

**Comment by MRezaNasirloo** [comment]
I'm creating a pull request for this stay tune
@rbro112 is it ok with you?

**Comment by wching** [comment]
that sounds awesome @MRezaNasirloo :)

**Comment by RahulSDeshpande** [comment]
Any update guys?
