### ISSUE TITLE
NPE when set ViewPager null (in java context) (version 1.0.9)

### ISSUE THREAD

**Issue by KSeyffarth** [rbro112/Android-Indefinite-Pager-Indicator#35]
getting a KotlinNullPointerException: 
` kotlin.KotlinNullPointerException 
at com.rbrooks.indefinitepagerindicator.IndefinitePagerIndicator.attachToViewPager(IndefinitePagerIndicator.kt:220)`

When using in  java code 
`indefinitePagerIndicator.attachToViewPager(null);`

Could it be an issue with java in combination with kotlin?

Current work around is using:
`indefinitePagerIndicator.attachToRecyclerView(null);`

**Comment by wching** [comment]
@KSeyffarth is that still happening on the newest version?

**Comment by KSeyffarth** [comment]
@wching no, seems to be fixed.

Thank you for your reply.

**Comment by wching** [comment]
awesome sauce @KSeyffarth! Closing the issue as it is resolved.
