### ISSUE TITLE
minSdk slightly too high

### ISSUE THREAD

**Issue by kibotu** [rbro112/Android-Indefinite-Pager-Indicator#4]
are there any specific reasons why it has to be min sdk 21? i need at least 16 for compatibility reasons: https://developer.android.com/about/dashboards/index.html

**Comment by rbro112** [comment]
No specific reasons, just for convenience sake. I'll add compatibility very soon and let you know when version 16 is supported!

**Comment by rbro112** [comment]
Fixed with #5 .
